version: '3.3'

services:
  backend:
    build: ./back-end
    ports:
      - 8080:8080
    restart: always
  frontend:
    build: ./front-end
    depends_on:
      - backend
    ports:
      - 3001:3000
    volumes:
      - './front-end:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always